version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(module)s:%(funcName)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: #/home/<user>/<path_to>/configuration/bootstrap.log
    maxBytes: 10000000
    backupCount: 3
loggers:
  simpleExample:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [file]
